// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadDropper returns the embedded CollectionSpec for Dropper.
func LoadDropper() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DropperBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Dropper: %w", err)
	}

	return spec, err
}

// LoadDropperObjects loads Dropper and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DropperObjects
//	*DropperPrograms
//	*DropperMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDropperObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDropper()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DropperSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropperSpecs struct {
	DropperProgramSpecs
	DropperMapSpecs
}

// DropperSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropperProgramSpecs struct {
	BlockEgress  *ebpf.ProgramSpec `ebpf:"block_egress"`
	BlockIngress *ebpf.ProgramSpec `ebpf:"block_ingress"`
}

// DropperMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DropperMapSpecs struct {
	CfgIfindex *ebpf.MapSpec `ebpf:"cfg_ifindex"`
	CfgPort    *ebpf.MapSpec `ebpf:"cfg_port"`
}

// DropperObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDropperObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropperObjects struct {
	DropperPrograms
	DropperMaps
}

func (o *DropperObjects) Close() error {
	return _DropperClose(
		&o.DropperPrograms,
		&o.DropperMaps,
	)
}

// DropperMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDropperObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropperMaps struct {
	CfgIfindex *ebpf.Map `ebpf:"cfg_ifindex"`
	CfgPort    *ebpf.Map `ebpf:"cfg_port"`
}

func (m *DropperMaps) Close() error {
	return _DropperClose(
		m.CfgIfindex,
		m.CfgPort,
	)
}

// DropperPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDropperObjects or ebpf.CollectionSpec.LoadAndAssign.
type DropperPrograms struct {
	BlockEgress  *ebpf.Program `ebpf:"block_egress"`
	BlockIngress *ebpf.Program `ebpf:"block_ingress"`
}

func (p *DropperPrograms) Close() error {
	return _DropperClose(
		p.BlockEgress,
		p.BlockIngress,
	)
}

func _DropperClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dropper_bpfel.o
var _DropperBytes []byte
